Implementation of forward algorithm for addressing the likelihood problem in Hidden Markov
Models

In [1]:
import numpy as np

Declare States and Observables

In [16]:
state = ['Sunny', 'Rainy']  # Hidden State
obs = ['Paint', 'Clean', 'Shop', 'Bike']  # Observation Sequence
pi = [0.6, 0.4]  # Initial Probabilities
A = np.array([[0.8, 0.2], [0.4, 0.6]])  # Transition Probabilities
b = np.array(([0.4, 0.1, 0.2, 0.3], [0.3, 0.45, 0.2, 0.05]))  # Emission Probabilities

forward_var = np.zeros((len(state), len(obs)))

observables = [0]  # Observable count

print(f"Hidden State: {state}")
print(f"Observation Sequence: {obs}\n")
print(f"Initial Probabilities: {pi}\n")
print(f"Transition Probabilities:\n{A}\n")
print(f"Emission Probabilities:\n{b}\n")

Hidden State: ['Sunny', 'Rainy']
Observation Sequence: ['Paint', 'Clean', 'Shop', 'Bike']

Initial Probabilities: [0.6, 0.4]

Transition Probabilities:
[[0.8 0.2]
 [0.4 0.6]]

Emission Probabilities:
[[0.4  0.1  0.2  0.3 ]
 [0.3  0.45 0.2  0.05]]



In [17]:
# Forward Initialization
def initialization():
    for i in range(len(state)):
        pi_i = pi[i]
        b_i = b[i, 0]
        at_i = pi_i * b_i

        forward_var[i, observables[0]] = at_i
    observables[0] += 1

In [18]:
initialization()

print(f"Forward Variables:\n{forward_var}\n")

Forward Variables:
[[0.24 0.   0.   0.  ]
 [0.12 0.   0.   0.  ]]



In [19]:
# Forward Recursion
def recursion():
    temp_res = []
    m, n = b.shape

    for j in range(1, n):
        for i in range(len(state)):
            for k in range(len(state)):
                at_j = forward_var[k, j - 1] * A[k, i]
                temp_res.append(round(at_j, 7))
            
            at_j = sum(s * b[i, observables[0]] for s in temp_res)
            forward_var[i, observables[0]] = at_j
            temp_res.clear()

        observables[0] += 1

In [20]:
recursion()

print(f"Forward Variables:\n{forward_var}\n")

Forward Variables:
[[0.24      0.024     0.00816   0.0028512]
 [0.12      0.054     0.00744   0.0003048]]



In [21]:
# Forward Termination
def termination():
    temp = []
    
    for i in range(len(state)):
        at_i = forward_var[i, -1]
        temp.append(at_i)
        
    p_o_lambda = sum(temp)
    temp.clear()

    return p_o_lambda

In [22]:
p_O_lambda = termination()

print(f"Forward Variables:\n{forward_var}\n")
print(f"P(O|λ): {round(p_O_lambda, 7)}\n")

Forward Variables:
[[0.24      0.024     0.00816   0.0028512]
 [0.12      0.054     0.00744   0.0003048]]

P(O|λ): 0.003156

