Implementation of Viterbi algorithm for addressing the decoding problem in Hidden Markov
Models

In [1]:
import numpy as np

Declare States and Observables

In [12]:
state = ['Fair', 'Biased']  # Hidden State
obs = ['Tails', 'Tails', 'Head', 'Tails']  # Observation Sequence
pi = [0.6, 0.4]  # Initial Probabilities
A = np.array([[0.7, 0.3], [0.4, 0.6]])  # Transition Probabilities
b = np.array(([0.5, 0.5, 0.5, 0.5], [0.2, 0.2, 0.8, 0.2])) # Emission Probabilities

viterbi_var = np.zeros((len(state), len(obs)))
sai = np.zeros((len(state), len(obs) + 1), dtype=int)

observables = [0]  # Observable count

print(f"Hidden State: {state}")
print(f"Observation Sequence: {obs}\n")
print(f"Initial Probabilities: {pi}\n")
print(f"Transition Probabilities:\n{A}\n")
print(f"Emission Probabilities:\n{b}\n")
print(f"Sai Array:\n{sai}\n")

Hidden State: ['Fair', 'Biased']
Observation Sequence: ['Tails', 'Tails', 'Head', 'Tails']

Initial Probabilities: [0.6, 0.4]

Transition Probabilities:
[[0.7 0.3]
 [0.4 0.6]]

Emission Probabilities:
[[0.5 0.5 0.5 0.5]
 [0.2 0.2 0.8 0.2]]

Sai Array:
[[0 0 0 0 0]
 [0 0 0 0 0]]



In [13]:
# Viterbi Initialization
def initialization():
    for i in range(len(state)):
        pi_i = pi[i]
        b_i = b[i, 0]
        at_i = pi_i * b_i

        viterbi_var[i, observables[0]] = at_i
        sai[i, observables[0]] = 0
    observables[0] += 1

In [14]:
initialization()

print(f"Viterbi Variables:\n{viterbi_var}\n")
print(f"Sai Array:\n{sai}")

Viterbi Variables:
[[0.3  0.   0.   0.  ]
 [0.08 0.   0.   0.  ]]

Sai Array:
[[0 0 0 0 0]
 [0 0 0 0 0]]


In [15]:
# Viterbi Recursion
def recursion():
    temp_res = []
    m, n = b.shape

    for j in range(1, n):
        for i in range(len(state)):
            for k in range(len(state)):
                at_j = viterbi_var[k, j - 1] * A[k, i]
                temp_res.append(round(at_j, 7))

            at_j = max(temp_res) * b[i, observables[0]]
            viterbi_var[i, observables[0]] = at_j
            sai[i, observables[0]] = np.argmax(temp_res)
            temp_res.clear()

        observables[0] += 1

In [16]:
recursion()

print(f"Viterbi Variables:\n{viterbi_var}\n")
print(f"Sai Array:\n{sai}")

Viterbi Variables:
[[0.3       0.105     0.03675   0.0128625]
 [0.08      0.018     0.0252    0.003024 ]]

Sai Array:
[[0 0 0 0 0]
 [0 0 0 1 0]]


In [17]:
# Viterbi Termination
def termination():
    temp = []
    
    for i in range(len(state)):
        at_i = viterbi_var[i, -1]
        temp.append(at_i)
        
        sai[i, observables[0]] = np.argmax(temp)
    max_viterbi = max(temp)
    temp.clear()

    return max_viterbi

In [18]:
max_viterbi_val = termination()

print(f"Viterbi Variables:\n{viterbi_var}\n")
print(f"Maximized Viterbi Variables: {round(max_viterbi_val, 7)}\n")
print(f"Sai Array:\n{sai}")

Viterbi Variables:
[[0.3       0.105     0.03675   0.0128625]
 [0.08      0.018     0.0252    0.003024 ]]

Maximized Viterbi Variables: 0.0128625

Sai Array:
[[0 0 0 0 0]
 [0 0 0 1 0]]


In [19]:
# Backtracking to find Hidden State Sequence
def backtrack():
    best_path = np.zeros(len(obs), dtype=int)
    best_path_seq = []
    
    best_path[-1] = sai[0, observables[0]]

    for i in range(observables[0] - 2, -1, -1):
        best_path[i] = sai[best_path[i + 1], i + 1]
        
    for j in best_path:
        best_path_seq.append(state[j])
    
    return best_path_seq

In [20]:
hidden_state_seq = backtrack()
print(f"Hidden State Sequence: \n{hidden_state_seq}\n")

Hidden State Sequence: 
['Fair', 'Fair', 'Fair', 'Fair']

